flaskApp/__init__.py
import os
import shutil
from flask import Flask
from flaskApp.routes import main_blueprint

def App():
    #create new folders
    os.makedirs(os.path.join('flaskApp','images'),exist_ok=True)
    os.makedirs(os.path.join('flaskApp','inpainted'),exist_ok=True)
    os.makedirs(os.path.join('flaskApp','masks'),exist_ok=True)

    app = Flask(__name__)
    app.register_blueprint(main_blueprint)

    return app

flaskApp/routes.py
import os
from flask import render_template, redirect, send_from_directory, redirect
from flask import current_app, request
from flask import Blueprint
from flaskApp.PatchGANgenerator import inpaint, format

main_blueprint = Blueprint('main', __name__)

@main_blueprint.route('/')
def index():
    return render_template('index.html')

@main_blueprint.route('/upload', methods=['POST'])
def upload():
    if 'file' not in request.files or request.files['file'].filename== '':
        return redirect(request.url)
    
    file = request.files['file']
    # Save the uploaded file to a folder on the server
    file.save('flaskApp/images/' + file.filename)
    
    #convert it into the right format
    format(file.filename)

    # Display the uploaded image
    return render_template('upload.html', filename=file.filename)

@main_blueprint.route('/images/<filename>')
def display_image(filename):
    root_dir = current_app.root_path
    return send_from_directory(os.path.join(root_dir, 'images'), filename)

@main_blueprint.route('/result',methods=['POST'])
def result():
    data = request.get_json()[0]
    filename = data['file'][len('http://127.0.0.1:5000/images/'):]
    inpaint(filename , int(data['x']) , int(data['y']))
    return render_template("result.html" , filename=filename)

@main_blueprint.route('/masks/<filename>')
def masked(filename):
    root_dir = current_app.root_path
    return send_from_directory(os.path.join(root_dir, 'masks'), filename)

@main_blueprint.route('/inpainted/<filename>')
def inpainted(filename):
    root_dir = current_app.root_path
    return send_from_directory(os.path.join(root_dir, 'inpainted'), filename)

@main_blueprint.route('/redirect')
def redirect_to_home():
    return redirect('/')

flaskApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    {%block head%}{%endblock%}
    <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}"/>
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <div class="container text-center">
        <div id="particles-js"></div>
        <div id = "overlay">
            <h1 class="mb-4">Image Inpainting using GANs</h1>
            <div class="row justify-content-center" id="well">
                {%block body%}{%endblock%}
            </div>
        </div>
    </div>

    <script src="{{url_for('static',filename='js/particles.js')}}"></script>
    <script src="{{url_for('static',filename='js/app.js')}}"></script>
</body>
</html>

flaskApp/templates/index.html
{%extends 'base.html' %}

{%block head%}
    <style>
        .form-control{
            margin:auto;
            width:50%;
            margin-bottom:10px;
        }
    </style>
{%endblock%}

{%block body%}

<form action = "/upload" method="post" enctype="multipart/form-data">
    <input class = "form-control" type="file" name="file" accept="image/*">
    <input class="btn btn-primary" type="submit" value="Upload!">
</form>

{%endblock%}

flaskApp/templates/result.html
{%extends 'base.html' %}


{%block head%}
<style>
    #result{
        width :128px;
        height:128px;
        }
    #container{
        margin:10px;
        display : inline-block;
        width : 150px;
    }
    h2 {
        color:black;
        width:128px;
    }
</style>
{%endblock%}


{%block body%}

    <div id="container"><h2>Original</h2><img id="result" src="{{url_for('main.display_image',filename=filename)}}" alt="Uploaded Image"></div>
    <div id="container"><h2>Masked</h2><img id="result" src="{{url_for('main.masked',filename=filename)}}" alt="Uploaded Image"></div>
    <div id="container"><h2>Inpainted</h2><img id="result" src="{{url_for('main.inpainted',filename=filename)}}" alt="Uploaded Image"></div>
    <form action="\redirect" method=" POST " enctype="multipart/form-data">
        <input class="btn btn-primary" type="submit" id="Home"value="Home" onclick="home()">
    </form>
    
{%endblock%}

flaskApp/templates/upload.html
{%extends 'base.html' %}

{%block head%}
    <link rel="stylesheet" href="{{url_for('static',filename='css/upload.css')}}"/>
{%endblock%}

{%block body%}

<div>
    <div id="image">
        <div name = "mask" id="patch"></div>
        <img id ="sample" src="{{url_for('main.display_image',filename=filename)}}" alt="Uploaded Image">
    </div>
    <input type="submit" value="Inpaint!" id="Inpaint" class="btn btn-primary" onclick="send_data()">
</div>

<script src="{{url_for('static',filename='js/draggable.js')}}"></script>
<script src="{{url_for('static',filename='js/get_cords.js')}}"></script>

{%endblock%}